{
    'name': 'Addons Sekolah',
    'version': '1.0',
    'summary': 'Modul untuk manajemen sekolah',
    'sequence': -100,
    'description': """Modul ini mengelola siswa, kelas, guru, jadwal, dan mata pelajaran.""",
    'category': 'Education',
    'website': 'https://www.yourwebsite.com',
    'author': 'Dion Tambunan',
    'depends': ['base'],
    'data': [
        'security/ir.model.access.csv',
        'views/siswa_views.xml',
        'views/kelas_views.xml',
        'views/guru_views.xml',
        'views/jadwal_views.xml',
        'views/mata_pelajaran_views.xml',
        'views/menu_views.xml',
    ],
    'demo': [],
    'qweb': [],
    'installable': True,
    'application': True,
    'auto_install': False,
}